# Generated by Django 5.0.2 on 2024-02-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elonsucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='transactions',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='block',
            name='transactions',
            field=models.ManyToManyField(to='elonsucks.transaction'),
        ),
    ]
