# Generated by Django 5.0.2 on 2024-02-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elonsucks', '0002_alter_block_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
