# Generated by Django 5.0.2 on 2024-02-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elonsucks', '0002_remove_block_transactions_delete_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
