# Generated by Django 5.0.2 on 2024-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elonsucks', '0005_node_alter_block_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='proof',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
